import { cn } from "@/lib/utils";
import React from "react";

const FloatingDots = () => {
  const dots = [
    {
      x: 6,
      y: 12,
      size: 3,
      opacity: 0.18,
      color: "var(--indigo)",
      duration: 7.2,
      delay: 0.4,
      blur: 1,
      driftX: 8,
      driftY: -16,
    },
    {
      x: 14,
      y: 64,
      size: 5,
      opacity: 0.12,
      color: "var(--cyan)",
      duration: 9.5,
      delay: 1.8,
      blur: 2,
      driftX: -6,
      driftY: -20,
    },
    {
      x: 8,
      y: 43,
      size: 2,
      opacity: 0.25,
      color: "white",
      duration: 6.3,
      delay: 2.1,
      blur: 2,
      driftX: 5,
      driftY: -10,
    },
    {
      x: 31,
      y: 82,
      size: 4,
      opacity: 0.14,
      color: "var(--indigo)",
      duration: 8.4,
      delay: 0.7,
      blur: 1,
      driftX: 9,
      driftY: -18,
    },
    {
      x: 42,
      y: 18,
      size: 6,
      opacity: 0.1,
      color: "var(--cyan)",
      duration: 10.2,
      delay: 3.4,
      blur: 2,
      driftX: -12,
      driftY: -22,
    },
    {
      x: 49,
      y: 57,
      size: 3,
      opacity: 0.18,
      color: "white",
      duration: 7.8,
      delay: 1.3,
      blur: 2,
      driftX: 7,
      driftY: -12,
    },
    {
      x: 58,
      y: 8,
      size: 2,
      opacity: 0.2,
      color: "var(--indigo)",
      duration: 6.7,
      delay: 4.2,
      blur: 1,
      driftX: 6,
      driftY: -15,
    },
    {
      x: 66,
      y: 35,
      size: 5,
      opacity: 0.13,
      color: "var(--cyan)",
      duration: 8.8,
      delay: 2.9,
      blur: 2,
      driftX: -8,
      driftY: -18,
    },
    {
      x: 74,
      y: 73,
      size: 3,
      opacity: 0.22,
      color: "white",
      duration: 7.1,
      delay: 0.9,
      blur: 2,
      driftX: 5,
      driftY: -14,
    },
    {
      x: 82,
      y: 22,
      size: 4,
      opacity: 0.15,
      color: "var(--indigo)",
      duration: 9.7,
      delay: 3.7,
      blur: 1,
      driftX: -9,
      driftY: -20,
    },
    {
      x: 91,
      y: 48,
      size: 6,
      opacity: 0.1,
      color: "var(--cyan)",
      duration: 10.6,
      delay: 2.5,
      blur: 2,
      driftX: 12,
      driftY: -24,
    },
    {
      x: 88,
      y: 88,
      size: 2,
      opacity: 0.2,
      color: "white",
      duration: 6.9,
      delay: 4.6,
      blur: 2,
      driftX: -5,
      driftY: -12,
    },
    {
      x: 52,
      y: 91,
      size: 5,
      opacity: 0.12,
      color: "var(--indigo)",
      duration: 9.1,
      delay: 1.5,
      blur: 1,
      driftX: 10,
      driftY: -16,
    },
    {
      x: 17,
      y: 92,
      size: 3,
      opacity: 0.18,
      color: "var(--cyan)",
      duration: 8.2,
      delay: 2.7,
      blur: 2,
      driftX: -7,
      driftY: -14,
    },
    {
      x: 95,
      y: 8,
      size: 2,
      opacity: 0.24,
      color: "white",
      duration: 7.4,
      delay: 0.6,
      blur: 2,
      driftX: 4,
      driftY: -10,
    },
  ];

  return (
    <>
      {dots.map(
        (
          { x, y, size, opacity, color, blur, duration, delay, driftX, driftY },
          index,
        ) => (
          <span
            key={index}
            className={cn("absolute rounded-full")}
            style={{
              left: `${x}%`,
              top: `${y}%`,
              width: size,
              height: size,
              opacity: opacity,
              background: color,
              filter: `blur(${blur}px)`,
              animation: `float-dot ${duration}s ease-in-out ${delay}s infinite`,
              "--drift-x": `${driftX}px`,
              "--drift-y": `${driftY}px`,
            }}
          />
        ),
      )}
    </>
  );
};

export default FloatingDots;
